### ISSUE TITLE
Download HiC-Pro Singularity image

### ISSUE THREAD

**Issue by ghost** [data-fun/3d-genome-builder#6]
I am trying to download the HiC-Pro Singularity image using the following command: "wget --ciphers=DEFAULT:@SECLEVEL=1 https://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/hicpro_3.1.0_ubuntu.img -P images". However, I am getting an error message that reads: "--2023-05-03 15:53:22--  https://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/hicpro_3.1.0_ubuntu.img Résolution de zerkalo.curie.fr (zerkalo.curie.fr)… 193.49.205.28 Connexion à zerkalo.curie.fr (zerkalo.curie.fr)|193.49.205.28|:443… connecté. requête HTTP transmise, en attente de la réponse… 404 Not Found 2023-05-03 15:53:22 erreur 404 : Not Found." How can I resolve this issue?

**Comment by pierrepo** [comment]
Hi @gayahaber thank you for your message. It looks like there is an issue with the Institute Curie web server that hosts the HiC-Pro Singularity image. I reported this issue [here](https://github.com/nservant/HiC-Pro/issues/565#issuecomment-1533232997).

**Comment by pierrepo** [comment]
Hey @gayahaber do you want me to share the HiC-Pro Singularity image I have with you?

**Comment by gayahaber** [comment]
Hi yes please.

**Comment by gayahaber** [comment]
Hi @pierrepo  yes please.

**Comment by pierrepo** [comment]
Here it is: https://www.swisstransfer.com/d/26cb4d32-f737-4725-b167-f0ea3af0b6a8
The link is valid one month.

Checksum:
```
$ md5sum images/*
d480e636397c14e187608e50309eb9af  images/hicpro_3.1.0_ubuntu.img
```

**Comment by gayahaber** [comment]
Thank you.

**Comment by pierrepo** [comment]
Hello @hanshanmengqi 
The `https://zerkalo.curie.fr/` web server looks up again. Could you retry?

**Comment by pierrepo** [comment]
@hanshanmengqi 
Here it is: https://www.swisstransfer.com/d/ff93fc3a-2724-461b-a637-b57ed3b56213
The link is valid for one month.

Checksum:
```
$ md5sum images/*
d480e636397c14e187608e50309eb9af  images/hicpro_3.1.0_ubuntu.img
```

**Comment by hanshanmengqi** [comment]
Thank you! I got it.

**Comment by pierrepo** [comment]
Dear all,

@nservant kindly archived the HiC-Pro Singularity image on [Zenodo](https://zenodo.org/record/8376626).

I added this alternate download link in the documentation.
