### ISSUE TITLE
Additional parameters for HiC Pro

### ISSUE THREAD

**Issue by gaellelelandais** [data-fun/3d-genome-builder#9]
Dear @pierrepo,

I would like to be able to specify an additional parameter for HiC Pro within the 3DGB [configuration file](https://github.com/data-fun/3d-genome-builder/blob/master/config_template.yml). This parameter is called [LIGATION SITE]. As described [here]( https://nservant.github.io/HiC-Pro/MANUAL.html#setting-the-configuration-file), the expected information is a short sequence, such as "AAGCTAGCTT".

Do you think it would be possible to create an updated version of the 3DGB workflow to include this functionality? Let me know if you need more information. And thanks for your help.

Gaëlle

**Comment by pierrepo** [comment]
Sure. That looks possibles. I could work on it in January.

**Comment by gaellelelandais** [comment]
Dear @pierrepo ,

I know you have been very busy the last few months. But several users are asking for this update. Do you think you will find the time to fix it before the summer?

Thank you very much,

Gaëlle

**Comment by gaellelelandais** [comment]
Dear @pierrepo ,

Sorry to insist on this, but do you think a patch can be added to 3DGB soon?
Thank you for your reply.

Gaëlle
